# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G_31p9bbTacjbvz7TXkMlzmgd6Wj7QZZ
"""

!pip install streamlit pandas

import streamlit as st
import pandas as pd

def main():
    st.title("ML/AI Interview Question Chatbot")

    uploaded_file = st.file_uploader("Upload your ML/AI interview questions CSV file", type=["csv"])

    if uploaded_file is not None:
        df = pd.read_csv(uploaded_file)

        levels = ['Beginner', 'Medium', 'Advanced']
        level = st.selectbox("Choose difficulty level:", levels)

        topics = df[df['level'] == level]['topic'].unique()
        selected_topic = st.selectbox("Select topic (optional):", options=[''] + list(topics))

        if selected_topic != '':
            filtered = df[(df['level'] == level) & (df['topic'] == selected_topic)]
        else:
            filtered = df[df['level'] == level]

        if filtered.empty:
            st.warning("Sorry, no questions found for your selection.")
        else:
            st.success(f"Found {len(filtered)} questions. Click on a question to see the answer:")

            for _, row in filtered.iterrows():
                with st.expander(row['question']):
                    st.write(row['answer'])

if __name__ == "__main__":
    main()