# -*- coding: utf-8 -*-
"""ML QUES AND CHATBOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pLka93Puj53Oy2zwybttEi_oxlotPbY
"""

from google.colab import files
import pandas as pd
import io


uploaded = files.upload()

# file uplaod krr dnege hum
filename = next(iter(uploaded))

# CSV read karenge
df = pd.read_csv(io.BytesIO(uploaded[filename]))

print(f"File '{filename}' uploaded successfully!")

# Dataframe ka preview lenge
df.head()

def chatbot():
    print("Welcome to ML/AI Interview Question Chatbot!")
    levels = ['Beginner', 'Medium', 'Advanced']

    # Level select karna
    level = input("Choose difficulty level (Beginner/Medium/Advanced): ").capitalize()
    while level not in levels:
        level = input("Please enter Beginner, Medium, or Advanced only: ").capitalize()

    # Topics dikhao
    topics = df['topic'].unique()
    print("\nAvailable topics:")
    for i, topic in enumerate(topics, 1):
        print(f"{i}. {topic}")
    topic_choice = input("Enter topic number or press Enter to skip: ")

    if topic_choice.isdigit() and 1 <= int(topic_choice) <= len(topics):
        selected_topic = topics[int(topic_choice) - 1]
        filtered = df[(df['level'] == level) & (df['topic'] == selected_topic)]
    else:
        filtered = df[df['level'] == level]

    if filtered.empty:
        print("Sorry, no questions found for your selection.")
        return

    print(f"\nFound {len(filtered)} questions. Press Enter to see each answer, 'q' to quit.")

    for idx, row in filtered.iterrows():
        print(f"\nQ: {row['question']}")
        ans = input("Press Enter to see answer or 'q' to quit: ")
        if ans.lower() == 'q':
            print("Thanks for using chatbot!")
            break
        print(f"A: {row['answer']}")